import createSet from "./createSet";

/**
 * Taken from https://developer.mozilla.org/en-US/docs/Glossary/Empty_element
 * and https://developer.mozilla.org/en-US/docs/Web/SVG/Element.
 */
export default createSet([
  "area",
  "base",
  "br",
  "col",
  "defs",
  "embed",
  "hr",
  "img",
  "input",
  "keygen",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
  "animate",
  "animateMotion",
  "animateTransform",
  "circle",
  "clipPath",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComposite",
  "feConvolveMatrix",
  "feDisplacementMap",
  "feDropShadow",
  "feFlood",
  "feGaussianBlur",
  "feImage",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpotLight",
  "feTile",
  "feTurbulence",
  "hatchpath",
  "image",
  "line",
  "mpath",
  "path",
  "polygon",
  "polyline",
  "rect",
  "set",
  "stop",
  "use",
  "view",
]);
