export enum RenderMode {
  BLOCK,
  INLINE,
}

export interface RenderDefinition {
  mode: RenderMode;
  forceBreak?: boolean;
  forceBreakChildren?: boolean;
  forceClose?: boolean;
  preformatted?: boolean;
  selfClosing?: boolean;
}

// prettier-ignore
const renderDefinitions: [string, RenderDefinition][] = [
  ["applet",            { mode: RenderMode.INLINE }],
  ["audio",             { mode: RenderMode.INLINE }],
  ["b",                 { mode: RenderMode.INLINE }],
  ["basefont",          { mode: RenderMode.INLINE }],
  ["bdi",               { mode: RenderMode.INLINE }],
  ["bdo",               { mode: RenderMode.INLINE }],
  ["bgsound",           { mode: RenderMode.INLINE }],
  ["big",               { mode: RenderMode.INLINE }],
  ["blink",             { mode: RenderMode.INLINE }],
  ["block-quote",       { mode: RenderMode.INLINE }],
  ["button",            { mode: RenderMode.INLINE }],
  ["canvas",            { mode: RenderMode.INLINE }],
  ["caption",           { mode: RenderMode.INLINE }],
  ["center",            { mode: RenderMode.INLINE }],
  ["cite",              { mode: RenderMode.INLINE }],
  ["code",              { mode: RenderMode.INLINE }],
  ["colgroup",          { mode: RenderMode.INLINE }],
  ["content",           { mode: RenderMode.INLINE }],
  ["data",              { mode: RenderMode.INLINE }],
  ["del",               { mode: RenderMode.INLINE }],
  ["dfn",               { mode: RenderMode.INLINE }],
  ["dir",               { mode: RenderMode.INLINE }],
  ["em",                { mode: RenderMode.INLINE }],
  ["font",              { mode: RenderMode.INLINE }],
  ["frame",             { mode: RenderMode.INLINE }],
  ["frameset",          { mode: RenderMode.INLINE }],
  ["iframe",            { mode: RenderMode.INLINE }],
  ["ins",               { mode: RenderMode.INLINE }],
  ["isindex",           { mode: RenderMode.INLINE }],
  ["kbd",               { mode: RenderMode.INLINE }],
  ["label",             { mode: RenderMode.INLINE }],
  ["legend",            { mode: RenderMode.INLINE }],
  ["listing",           { mode: RenderMode.INLINE }],
  ["map",               { mode: RenderMode.INLINE }],
  ["mark",              { mode: RenderMode.INLINE }],
  ["marquee",           { mode: RenderMode.INLINE }],
  ["math",              { mode: RenderMode.INLINE }],
  ["menu",              { mode: RenderMode.INLINE }],
  ["menuitem",          { mode: RenderMode.INLINE }],
  ["meter",             { mode: RenderMode.INLINE }],
  ["multicol",          { mode: RenderMode.INLINE }],
  ["nextid",            { mode: RenderMode.INLINE }],
  ["nobr",              { mode: RenderMode.INLINE }],
  ["noembed",           { mode: RenderMode.INLINE }],
  ["noframes",          { mode: RenderMode.INLINE }],
  ["noscript",          { mode: RenderMode.INLINE }],
  ["object",            { mode: RenderMode.INLINE }],
  ["output",            { mode: RenderMode.INLINE }],
  ["picture",           { mode: RenderMode.INLINE }],
  ["plain-text",        { mode: RenderMode.INLINE }],
  ["portal",            { mode: RenderMode.INLINE }],
  ["progress",          { mode: RenderMode.INLINE }],
  ["q",                 { mode: RenderMode.INLINE }],
  ["rb",                { mode: RenderMode.INLINE }],
  ["rp",                { mode: RenderMode.INLINE }],
  ["rt",                { mode: RenderMode.INLINE }],
  ["rtc",               { mode: RenderMode.INLINE }],
  ["ruby",              { mode: RenderMode.INLINE }],
  ["s",                 { mode: RenderMode.INLINE }],
  ["samp",              { mode: RenderMode.INLINE }],
  ["shadow",            { mode: RenderMode.INLINE }],
  ["slot",              { mode: RenderMode.INLINE }],
  ["small",             { mode: RenderMode.INLINE }],
  ["spacer",            { mode: RenderMode.INLINE }],
  ["span",              { mode: RenderMode.INLINE }],
  ["strike",            { mode: RenderMode.INLINE }],
  ["strong",            { mode: RenderMode.INLINE }],
  ["sub",               { mode: RenderMode.INLINE }],
  ["sup",               { mode: RenderMode.INLINE }],
  ["svg",               { mode: RenderMode.INLINE }],
  ["tbody",             { mode: RenderMode.INLINE }],
  ["td",                { mode: RenderMode.INLINE }],
  ["template",          { mode: RenderMode.INLINE }],
  ["tfoot",             { mode: RenderMode.INLINE }],
  ["th",                { mode: RenderMode.INLINE }],
  ["thead",             { mode: RenderMode.INLINE }],
  ["time",              { mode: RenderMode.INLINE }],
  ["title",             { mode: RenderMode.INLINE }],
  ["tr",                { mode: RenderMode.INLINE }],
  ["tt",                { mode: RenderMode.INLINE }],
  ["u",                 { mode: RenderMode.INLINE }],
  ["var",               { mode: RenderMode.INLINE }],
  ["video",             { mode: RenderMode.INLINE }],
  ["xmp",               { mode: RenderMode.INLINE }],
  ["a",                 { mode: RenderMode.INLINE}],
  ["abbr",              { mode: RenderMode.INLINE}],
  ["acronym",           { mode: RenderMode.INLINE}],
  ["image",             { mode: RenderMode.INLINE, selfClosing: true }],
  ["line",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["mpath",             { mode: RenderMode.INLINE, selfClosing: true }],
  ["path",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["polygon",           { mode: RenderMode.INLINE, selfClosing: true }],
  ["polyline",          { mode: RenderMode.INLINE, selfClosing: true }],
  ["rect",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["set",               { mode: RenderMode.INLINE, selfClosing: true }],
  ["stop",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["use",               { mode: RenderMode.INLINE, selfClosing: true }],
  ["view",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["circle",            { mode: RenderMode.INLINE, selfClosing: true }],
  ["clipPath",          { mode: RenderMode.INLINE, selfClosing: true }],
  ["ellipse",           { mode: RenderMode.INLINE, selfClosing: true }],
  ["feBlend",           { mode: RenderMode.INLINE, selfClosing: true }],
  ["feColorMatrix",     { mode: RenderMode.INLINE, selfClosing: true }],
  ["feComposite",       { mode: RenderMode.INLINE, selfClosing: true }],
  ["feConvolveMatrix",  { mode: RenderMode.INLINE, selfClosing: true }],
  ["feDisplacementMap", { mode: RenderMode.INLINE, selfClosing: true }],
  ["feDropShadow",      { mode: RenderMode.INLINE, selfClosing: true }],
  ["feFlood",           { mode: RenderMode.INLINE, selfClosing: true }],
  ["feGaussianBlur",    { mode: RenderMode.INLINE, selfClosing: true }],
  ["feImage",           { mode: RenderMode.INLINE, selfClosing: true }],
  ["feMergeNode",       { mode: RenderMode.INLINE, selfClosing: true }],
  ["feMorphology",      { mode: RenderMode.INLINE, selfClosing: true }],
  ["feOffset",          { mode: RenderMode.INLINE, selfClosing: true }],
  ["fePointLight",      { mode: RenderMode.INLINE, selfClosing: true }],
  ["feSpotLight",       { mode: RenderMode.INLINE, selfClosing: true }],
  ["feTile",            { mode: RenderMode.INLINE, selfClosing: true }],
  ["feTurbulence",      { mode: RenderMode.INLINE, selfClosing: true }],
  ["hatchpath",         { mode: RenderMode.INLINE, selfClosing: true }],
  ["animate",           { mode: RenderMode.INLINE, selfClosing: true }],
  ["animateMotion",     { mode: RenderMode.INLINE, selfClosing: true }],
  ["animateTransform",  { mode: RenderMode.INLINE, selfClosing: true }],
  ["source",            { mode: RenderMode.INLINE, selfClosing: true }],
  ["col",               { mode: RenderMode.INLINE, selfClosing: true }],
  ["area",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["base",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["defs",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["embed",             { mode: RenderMode.INLINE, selfClosing: true }],
  ["img",               { mode: RenderMode.INLINE, selfClosing: true }],
  ["keygen",            { mode: RenderMode.INLINE, selfClosing: true }],
  ["link",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["meta",              { mode: RenderMode.INLINE, selfClosing: true }],
  ["br",                { mode: RenderMode.INLINE, forceBreak: true, selfClosing: true }],
  ["address",           { mode: RenderMode.BLOCK }],
  ["article",           { mode: RenderMode.BLOCK }],
  ["aside",             { mode: RenderMode.BLOCK }],
  ["body",              { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["blockquote",        { mode: RenderMode.BLOCK }],
  ["details",           { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["datalist",          { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["dialog",            { mode: RenderMode.BLOCK }],
  ["dd",                { mode: RenderMode.BLOCK }],
  ["div",               { mode: RenderMode.BLOCK }],
  ["dl",                { mode: RenderMode.BLOCK }],
  ["dt",                { mode: RenderMode.BLOCK }],
  ["fieldset",          { mode: RenderMode.BLOCK }],
  ["figcaption",        { mode: RenderMode.BLOCK }],
  ["figure",            { mode: RenderMode.BLOCK }],
  ["footer",            { mode: RenderMode.BLOCK }],
  ["form",              { mode: RenderMode.BLOCK }],
  ["input",             { mode: RenderMode.INLINE, selfClosing: true }],
  ["g",                 { mode: RenderMode.BLOCK }],
  ["h1",                { mode: RenderMode.BLOCK }],
  ["h2",                { mode: RenderMode.BLOCK }],
  ["h3",                { mode: RenderMode.BLOCK }],
  ["h4",                { mode: RenderMode.BLOCK }],
  ["h5",                { mode: RenderMode.BLOCK }],
  ["h6",                { mode: RenderMode.BLOCK }],
  ["html",              { mode: RenderMode.BLOCK }],
  ["header",            { mode: RenderMode.BLOCK }],
  ["head",              { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["hgroup",            { mode: RenderMode.BLOCK }],
  ["hr",                { mode: RenderMode.BLOCK, selfClosing: true }],
  ["li",                { mode: RenderMode.BLOCK }],
  ["main",              { mode: RenderMode.BLOCK }],
  ["nav",               { mode: RenderMode.BLOCK }],
  ["ol",                { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["p",                 { mode: RenderMode.BLOCK }],
  ["pre",               { mode: RenderMode.BLOCK, preformatted: true }],
  ["section",           { mode: RenderMode.BLOCK }],
  ["select",            { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["optgroup",          { mode: RenderMode.BLOCK }],
  ["option",            { mode: RenderMode.BLOCK }],
  ["summary",           { mode: RenderMode.BLOCK }],
  ["script",            { mode: RenderMode.BLOCK, forceClose: true, forceBreakChildren: true },],
  ["style",             { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["param",             { mode: RenderMode.BLOCK, selfClosing: true }],
  ["table",             { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["ul",                { mode: RenderMode.BLOCK, forceBreakChildren: true }],
  ["track",             { mode: RenderMode.BLOCK, selfClosing: true }],
  ["textarea",          { mode: RenderMode.INLINE, preformatted: true }],
  ["wbr",               {mode: RenderMode. INLINE, selfClosing: true }],
];

export const tagRegistry: Map<string, RenderDefinition> = new Map<
  string,
  RenderDefinition
>();

const duplicatedTags: string[] = [];
for (const [tagName, renderDefinition] of renderDefinitions) {
  if (tagRegistry.has(tagName)) {
    duplicatedTags.push(tagName);
  }
  tagRegistry.set(tagName, renderDefinition);
}
if (duplicatedTags.length > 0) {
  throw new Error(duplicatedTags.join(", ") + " are duplicated");
}
